### ISSUE TITLE
ctest fails on windows

### ISSUE THREAD

**Issue by perabrahamsen** [daisy-model/daisy#28]
Following the build instructions on a fresh msys2, ctest fails.

The lastTest.log contains

Unable to find executable: check_daisy
Unable to find executable: test_daisy

I tried following the instructions under "Testing"

I needed 

pacman -S python 
pacman -S python-pip

and then got this:

$ pip install daisypy-test@git+https://github.com/daisy-model/daisypy-test
Collecting daisypy-test@ git+https://github.com/daisy-model/daisypy-test
  Cloning https://github.com/daisy-model/daisypy-test to /tmp/pip-install-swga6bu0/daisypy-test_9eb76340b13047d39c1ca65b25d491de
  Running command git clone --filter=blob:none --quiet https://github.com/daisy-model/daisypy-test /tmp/pip-install-swga6bu0/daisypy-test_9eb76340b13047d39c1ca65b25d491de
  Resolved https://github.com/daisy-model/daisypy-test to commit b58243c1fb70dbabff09242ae46f2a5e663eb358
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting daisypy-io@ git+https://github.com/daisy-model/daisypy-io (from daisypy-test@ git+https://github.com/daisy-model/daisypy-test)
  Cloning https://github.com/daisy-model/daisypy-io to /tmp/pip-install-swga6bu0/daisypy-io_6ba2978df9ee495f98095974066fa3e4
  Running command git clone --filter=blob:none --quiet https://github.com/daisy-model/daisypy-io /tmp/pip-install-swga6bu0/daisypy-io_6ba2978df9ee495f98095974066fa3e4
  Resolved https://github.com/daisy-model/daisypy-io to commit b6c8eb9ed3966f403b9d5077a0b14cf93ede76a7
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas (from daisypy-test@ git+https://github.com/daisy-model/daisypy-test)
  Downloading pandas-2.2.2.tar.gz (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 30.7 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Collecting meson-python==0.13.1
        Downloading meson_python-0.13.1-py3-none-any.whl.metadata (4.1 kB)
      Collecting meson==1.2.1
        Downloading meson-1.2.1-py3-none-any.whl.metadata (1.7 kB)
      Collecting wheel
        Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting Cython==3.0.5
        Downloading Cython-3.0.5-py2.py3-none-any.whl.metadata (3.2 kB)
      Collecting numpy>=2.0.0rc1
        Downloading numpy-2.0.0rc2.tar.gz (18.3 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 35.3 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [4 lines of output]

            meson-python: error: Could not find meson version 0.63.3 or newer, found ERROR: This python3 seems to be msys/python on MSYS2 Windows, but you are in a MinGW environment
            meson-python: error: ERROR: Please install and use mingw-w64-x86_64-python3 and/or mingw-w64-x86_64-meson with Pacman
            meson-python: error: .
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      × Encountered error while generating package metadata.
      ╰─> See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

ctest still fails with the same errors.

**Comment by orting** [comment]
Pandas needs to be installed with pacman, not pip. README has been updated with new instructions
